"""Instagram: cuenta conectada, fotos guardadas e id de origen

Revision ID: b3e750fa9a56
Revises: 51cf02c16368
Create Date: 2026-08-09 17:56:04.666807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e750fa9a56'
down_revision = '51cf02c16368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instagram_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ig_user_id', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('oauth_state', sa.String(length=64), nullable=True),
    sa.Column('oauth_state_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # La restriccion va con nombre explicito: SQLite recrea la tabla entera para
    # alterarla y no puede hacerlo con una restriccion anonima.
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instagram_id', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint('uq_posts_instagram_id', ['instagram_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_posts_instagram_id', type_='unique')
        batch_op.drop_column('instagram_id')

    op.drop_table('media_assets')
    op.drop_table('instagram_account')
    # ### end Alembic commands ###
